// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAIm5m-pOIC67pcfMqiTM2UkUise4JiwM',
    appId: '1:701919807017:web:e101093bca0fa7c1057e38',
    messagingSenderId: '701919807017',
    projectId: 'my-first-project-firebase-jfq',
    authDomain: 'my-first-project-firebase-jfq.firebaseapp.com',
    storageBucket: 'my-first-project-firebase-jfq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABTpq9VqWqe3R98HZb9hl6AWtsneqEIjQ',
    appId: '1:701919807017:android:6c368710dc0e17cf057e38',
    messagingSenderId: '701919807017',
    projectId: 'my-first-project-firebase-jfq',
    storageBucket: 'my-first-project-firebase-jfq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-FdR67Q08k_Yq6At5s2vRiXjzA4Cp574',
    appId: '1:701919807017:ios:c02130eb53da322c057e38',
    messagingSenderId: '701919807017',
    projectId: 'my-first-project-firebase-jfq',
    storageBucket: 'my-first-project-firebase-jfq.appspot.com',
    iosClientId: '701919807017-3dnd9ek83pnpgmqeltemk4e8pov6vn5g.apps.googleusercontent.com',
    iosBundleId: 'quirino.jonas.exampleFirebase',
  );
}
